'use client'
import { useEffect,useState } from 'react'
import { createClient } from '@/lib/supabase/client'
import { useRouter } from 'next/navigation'

type Action={subject:string;topic:string;reason:string;minutes?:number;source:'recommendation'|'risk'|'plan';recommendationId?:string;recommendationStatus?:string}
export default function NextBestAction(){
  const router=useRouter()
  const [action,setAction]=useState<Action|null>(null)
  const [busy,setBusy]=useState(false)
  useEffect(()=>{let cancelled=false;void(async()=>{const {data:{session}}=await createClient().auth.getSession();if(!session)return;const headers={Authorization:`Bearer ${session.access_token}`};const [recommendations,risk,plan]=await Promise.all([fetch('/api/recommendations',{headers}),fetch('/api/student/learning-risk',{headers}),fetch('/api/agents/study-plan',{method:'POST',headers:{...headers,'Content-Type':'application/json'},body:JSON.stringify({timeBudgetMinutes:20})})]);const [rj,kj,pj]=await Promise.all([recommendations.ok?recommendations.json():{},risk.ok?risk.json():{},plan.ok?plan.json():{}]) as [{recommendations?:Array<{id:string;status:string;subject:string;topic:string;reason?:string}>},{risks?:Array<{level:string;subject:string;topic:string}>},{plan?:Array<{subject?:string;topic:string;reason?:string;estimated_minutes?:number}>}];const recommendation=rj.recommendations?.find(item=>item.status==='accepted'||item.status==='active');const highRisk=kj.risks?.find(item=>item.level==='high')??kj.risks?.[0];const planned=pj.plan?.[0];const selected:Action|null=recommendation?{subject:recommendation.subject,topic:recommendation.topic,reason:recommendation.reason||'Bu adım öğrenme planında en yüksek önceliğe sahip.',source:'recommendation',recommendationId:recommendation.id,recommendationStatus:recommendation.status}:highRisk?{subject:highRisk.subject,topic:highRisk.topic,reason:'Son çalışmaların bu konuyu kısa sürede tekrar etmenin yararlı olacağını gösteriyor.',source:'risk'}:planned?{subject:planned.subject||'Genel',topic:planned.topic,reason:planned.reason||'Çalışma planındaki sıradaki uygun adım.',minutes:planned.estimated_minutes,source:'plan'}:null;if(!cancelled)setAction(selected)})();return()=>{cancelled=true}},[])
  if(!action)return null
  const label={recommendation:'Öğrenme planına göre',risk:'Erken uyarıya göre',plan:'Çalışma rehberine göre'}[action.source]
  const href=`/quiz?subject=${encodeURIComponent(action.subject)}&topic=${encodeURIComponent(action.topic)}`
  async function start(){if(action.source!=='recommendation'||action.recommendationStatus==='accepted'){router.push(`${href}${action.recommendationId?`&recommendationId=${action.recommendationId}`:''}`);return}setBusy(true);const {data:{session}}=await createClient().auth.getSession();if(!session){setBusy(false);return}const response=await fetch('/api/recommendations',{method:'POST',headers:{Authorization:`Bearer ${session.access_token}`,'Content-Type':'application/json'},body:JSON.stringify({recommendationId:action.recommendationId,action:'accept'})});if(response.ok)router.push(`${href}&recommendationId=${action.recommendationId}`);else setBusy(false)}
  return <section style={{marginBottom:'1rem',padding:'18px',borderRadius:18,background:'linear-gradient(135deg,#29483d,#38705d)',color:'#fff',boxShadow:'0 10px 28px rgba(41,72,61,.22)'}}><div style={{fontSize:11,fontWeight:800,color:'#bdf5df',textTransform:'uppercase'}}>Şimdi ne çalışmalıyım?</div><div style={{fontSize:19,fontWeight:850,marginTop:5}}>{action.topic}</div><div style={{fontSize:12,color:'rgba(255,255,255,.82)',marginTop:5,lineHeight:1.55}}><strong>Neden:</strong> {action.reason}</div><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:10,marginTop:13}}><span style={{fontSize:10,color:'rgba(255,255,255,.65)'}}>{label}{action.minutes?` · yaklaşık ${action.minutes} dk`:''}</span><button disabled={busy} onClick={()=>void start()} style={{padding:'9px 13px',border:0,borderRadius:10,background:'#fdd31d',color:'#29483d',fontSize:11,fontWeight:850,cursor:'pointer'}}>{busy?'Açılıyor…':'Çalışmaya başla →'}</button></div></section>
}
