'use client'
import { useEffect, useState } from 'react'
import { createClient } from '@/lib/supabase/client'
export default function AdaptiveEvaluation() {
  const [studentId, setStudentId] = useState(''); const [cohort, setCohort] = useState('adaptive'); const [message, setMessage] = useState(''); const [report, setReport] = useState<any>(null)
  async function request(url: string, options?: RequestInit) { const { data: { session } } = await createClient().auth.getSession(); if (!session) return null; const r = await fetch(url, { ...options, headers: { Authorization: `Bearer ${session.access_token}`, ...(options?.headers || {}) } }); return r.ok ? r.json() : null }
  async function load() { setReport(await request('/api/admin/adaptive-evaluation')) }
  useEffect(() => { void load() }, [])
  async function assign() { setMessage(''); const data = await request('/api/admin/adaptive-evaluation/assign', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ studentId: studentId.trim(), cohort }) }); setMessage(data ? '✓ Kohort atandı ve baseline kaydedildi.' : 'Atama başarısız veya öğrenci zaten atanmış.'); if (data) { setStudentId(''); load() } }
  async function followUp() { setMessage(''); const data = await request('/api/admin/adaptive-evaluation/follow-up', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ studentId: studentId.trim() }) }); setMessage(data ? '✓ Follow-up snapshot kaydedildi.' : 'Açık değerlendirme bulunamadı.'); if (data) load() }
  return <div className="card" style={{ marginBottom: '1rem' }}><strong style={{ color: 'var(--primary)' }}>🧪 Adaptive Learning v3 pilotu</strong>{report && <div style={{ marginTop: 8, padding: 8, borderRadius: 8, background: report.interpretable ? 'var(--green-bg)' : 'var(--amber-bg)', color: report.interpretable ? 'var(--green)' : 'var(--amber)', fontSize: 12, fontWeight: 700 }}>{report.interpretable ? '✓ Sonuçlar yorumlanabilir' : '⚠️ Örneklem yetersiz veya dengesiz; sonuçlar henüz yorumlanamaz'}</div>}<div style={{ display: 'flex', gap: 8, marginTop: 10, flexWrap: 'wrap' }}><input className="input" value={studentId} onChange={e => setStudentId(e.target.value)} placeholder="Öğrenci UUID" style={{ flex: 1, minWidth: 220 }} /><select className="input" value={cohort} onChange={e => setCohort(e.target.value)} style={{ width: 130 }}><option value="adaptive">Adaptive</option><option value="standard">Standard</option></select><button className="btn btn-primary" onClick={assign} disabled={!studentId.trim()}>Ata</button><button className="btn" onClick={followUp} disabled={!studentId.trim()}>Follow-up al</button></div>{message && <div style={{ fontSize: 12, marginTop: 8, color: message.startsWith('✓') ? 'var(--green)' : 'var(--red)' }}>{message}</div>}{report?.cohorts && <div style={{ display: 'grid', gap: 6, marginTop: 12, fontSize: 12 }}>{report.cohorts.map((row: any) => <div key={row.cohort} style={{ borderTop: '1px solid var(--border)', paddingTop: 6 }}><strong>{row.cohort}</strong> · atanmış {row.assigned_sample} · tamamlanmış {row.completed_sample} · mastery kazanımı: {row.mastery_gain ?? '—'} · başarı kazanımı: {row.pct_gain ?? '—'}</div>)}</div>}</div>
}
