'use client'
import { useEffect, useState } from 'react'
import { createClient } from '@/lib/supabase/client'
export default function DataLifecycleRequests() {
  const [items, setItems] = useState<any[]>([])
  const [preview, setPreview] = useState<any>(null)
  const load = async () => { const { data: { session } } = await createClient().auth.getSession(); if (!session) return; const r = await fetch('/api/admin/data-lifecycle-requests', { headers: { Authorization: `Bearer ${session.access_token}` } }); if (r.ok) setItems(((await r.json()).requests || []).filter((item: any) => ['pending', 'verified', 'in_progress'].includes(item.status))) }
  useEffect(() => { void load() }, [])
  async function update(id: string, status: string) { const { data: { session } } = await createClient().auth.getSession(); if (!session) return; await fetch('/api/admin/data-lifecycle-requests', { method: 'PATCH', headers: { Authorization: `Bearer ${session.access_token}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ id, status }) }); load() }
  async function showPreview(id: string) { const { data: { session } } = await createClient().auth.getSession(); if (!session) return; const r = await fetch(`/api/admin/data-lifecycle-requests/${id}/preview`, { headers: { Authorization: `Bearer ${session.access_token}` } }); if (r.ok) setPreview(await r.json()) }
  async function execute(id: string) { const { data: { session } } = await createClient().auth.getSession(); if (!session) return; const r = await fetch(`/api/admin/data-lifecycle-requests/${id}/execute`, { method: 'POST', headers: { Authorization: `Bearer ${session.access_token}` } }); if (r.ok) { setPreview(null); load() } else { const data = await r.json().catch(() => null); alert(data?.error || 'Silme tamamlanamadı. Talep korunuyor.') } }
  return <div className="card" style={{ marginBottom: '1rem' }}><strong style={{ color: 'var(--primary)' }}>🔐 KVKK talepleri</strong>{items.length ? items.map(item => <div key={item.id} style={{ borderTop: '1px solid var(--border)', marginTop: 8, paddingTop: 8, fontSize: 12 }}><div><strong>{item.request_kind}</strong> · {item.status} · kapsam: {item.scope}</div><div style={{ color: 'var(--text3)', margin: '3px 0 7px' }}>Talep: {new Date(item.created_at).toLocaleString('tr-TR')}</div><button onClick={() => showPreview(item.id)} style={{ marginRight: 6 }}>Etkiyi gör</button>{item.status === 'pending' && <><button onClick={() => update(item.id, 'verified')} style={{ marginRight: 6 }}>Doğrula</button><button onClick={() => update(item.id, 'rejected')}>Reddet</button></>}{item.status === 'verified' && <button onClick={async () => { const { data: { session } } = await createClient().auth.getSession(); if (!session) return; await fetch(`/api/admin/data-lifecycle-requests/${item.id}/confirm`, { method: 'POST', headers: { Authorization: `Bearer ${session.access_token}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ confirm: true, previewConfirmed: true }) }); load() }}>İkinci onay</button>}{item.status === 'in_progress' && <button onClick={() => execute(item.id)} style={{ color: 'var(--red)', marginLeft: 6 }}>Kalıcı sil</button>}</div>) : <div style={{ marginTop: 8, fontSize: 12, color: 'var(--text3)' }}>Bekleyen KVKK talebi yok.</div>}{preview && <div style={{ marginTop: 12, padding: 10, background: 'var(--bg2)', borderRadius: 8, fontSize: 11 }}><strong>Etki önizlemesi</strong>{Object.entries(preview.preview || {}).map(([key, value]) => <div key={key}>{key}: {String(value)} kayıt</div>)}<div style={{ marginTop: 5, color: 'var(--red)' }}>Silme henüz çalıştırılmadı.</div></div>}</div>
}
