'use client'
import { useState } from 'react'

interface Misconception { id: string; subject: string; topic: string; label: string; evidence_count: number }
interface Content { id: string; misconception_id: string; short_explanation: string; correction_strategy: string; worked_example: string; check_question: { question?: string; answer?: string }; status: string; ai_model: string | null }

export default function MisconceptionMicroContent() {
  const [items,setItems]=useState<Misconception[]>([]); const [contents,setContents]=useState<Content[]>([])
  const [busy,setBusy]=useState(false); const [message,setMessage]=useState(''); const [notes,setNotes]=useState<Record<string,string>>({})
  async function load(){setBusy(true);const r=await fetch('/api/admin/misconception-micro-content');const d=await r.json();if(r.ok){setItems(d.misconceptions||[]);setContents(d.contents||[])}else setMessage(`❌ ${d.error}`);setBusy(false)}
  async function generate(misconceptionId:string){setBusy(true);setMessage('');const r=await fetch('/api/admin/misconception-micro-content',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({misconceptionId})});const d=await r.json();setMessage(r.ok?'✅ Uzman incelemesi için taslak hazırlandı.':`❌ ${d.error}`);if(r.ok)await load();setBusy(false)}
  async function generateBatch(){
    const batch=missingItems.slice(0,5); if(!batch.length)return
    setBusy(true); setMessage(`⏳ ${batch.length} taslak hazırlanıyor…`)
    let created=0
    for(const item of batch){
      const response=await fetch('/api/admin/misconception-micro-content',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({misconceptionId:item.id})})
      if(response.ok)created++
    }
    await load(); setMessage(`✅ ${created}/${batch.length} taslak uzman incelemesine gönderildi.`); setBusy(false)
  }
  async function decide(content:Content,decision:'approved'|'rejected'){setBusy(true);setMessage('');const r=await fetch('/api/admin/misconception-micro-content',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:content.id,decision,note:notes[content.id]||'',shortExplanation:content.short_explanation,correctionStrategy:content.correction_strategy,workedExample:content.worked_example,question:content.check_question.question||'',answer:content.check_question.answer||''})});const d=await r.json();setMessage(r.ok?'✅ Uzman kararı kaydedildi.':`❌ ${d.error}`);if(r.ok)await load();setBusy(false)}
  const contentByMisconception=new Map(contents.filter(c=>['draft','approved'].includes(c.status)).map(c=>[c.misconception_id,c]))
  const missingItems=items.filter(item=>!contentByMisconception.has(item.id))
  const update=(id:string,field:keyof Pick<Content,'short_explanation'|'correction_strategy'|'worked_example'>,value:string)=>setContents(current=>current.map(c=>c.id===id?{...c,[field]:value}:c))
  return <div className="card" style={{marginTop:16}}><div style={{fontWeight:700,fontSize:14,color:'var(--primary)'}}>🩹 Yanılgı Düzeltici Mikro İçerikleri</div><div style={{fontSize:12,color:'var(--text3)',margin:'4px 0 10px'}}>Yalnızca doğrulanmış yanılgılar için AI taslağı hazırlanır; öğrenciye açılmadan önce uzman onayı gerekir.</div><button className="btn btn-sm" disabled={busy} onClick={load}>{busy?'İşleniyor…':'Doğrulanmış yanılgıları yükle'}</button>{items.length>0&&<div style={{marginTop:10,padding:'9px 11px',borderRadius:8,background:'var(--bg2)',fontSize:12}}><strong>{items.length}</strong> doğrulanmış yanılgı · <strong>{missingItems.length}</strong> taslak bekliyor · <strong>{contents.filter(c=>c.status==='draft').length}</strong> uzman incelemesinde · <strong>{contents.filter(c=>c.status==='approved').length}</strong> yayımlanmış{missingItems[0]&&<><button className="btn btn-sm" style={{marginLeft:10}} disabled={busy} onClick={()=>generate(missingItems[0].id)}>Sıradaki taslağı hazırla</button><button className="btn btn-sm" style={{marginLeft:6}} disabled={busy} onClick={generateBatch}>İlk 5 taslağı hazırla</button></>}</div>}{message&&<div style={{fontSize:12,marginTop:8}}>{message}</div>}<div style={{display:'grid',gap:9,marginTop:10}}>{items.map(item=>{const c=contentByMisconception.get(item.id);return <div key={item.id} style={{border:'1px solid var(--border)',borderRadius:9,padding:10,fontSize:12}}><strong>{item.label}</strong><div style={{color:'var(--text3)',marginTop:2}}>{item.subject} → {item.topic} · {item.evidence_count} kanıt</div>{!c?<button className="btn btn-sm" style={{marginTop:7}} disabled={busy} onClick={()=>generate(item.id)}>AI taslağı hazırla</button>:<div style={{marginTop:7}}><div style={{color:c.status==='approved'?'#16a34a':'#7c3aed'}}>{c.status==='approved'?'Yayımlanmış':'Uzman incelemesi bekliyor'} · {c.ai_model||'manuel'}</div><textarea className="input" style={{width:'100%',marginTop:6}} disabled={c.status!=='draft'} value={c.short_explanation} onChange={e=>update(c.id,'short_explanation',e.target.value)}/><textarea className="input" style={{width:'100%',marginTop:6}} disabled={c.status!=='draft'} value={c.correction_strategy} onChange={e=>update(c.id,'correction_strategy',e.target.value)}/><textarea className="input" style={{width:'100%',marginTop:6}} disabled={c.status!=='draft'} value={c.worked_example} onChange={e=>update(c.id,'worked_example',e.target.value)}/>{c.status==='draft'&&<><input className="input" style={{width:'100%',marginTop:6}} placeholder="Uzman notu; rette zorunlu" value={notes[c.id]||''} onChange={e=>setNotes(n=>({...n,[c.id]:e.target.value}))}/><div style={{display:'flex',gap:6,marginTop:6}}><button className="btn btn-sm" disabled={busy} onClick={()=>decide(c,'approved')}>Onayla ve yayımla</button><button className="btn btn-sm" disabled={busy||!(notes[c.id]||'').trim()} onClick={()=>decide(c,'rejected')}>Reddet</button></div></>}</div>}</div>})}</div></div>
}
