'use client'
import { useEffect, useState } from 'react'
import { createClient } from '@/lib/supabase/client'

type Health = { period_hours:number; ai:{calls:number;p95_duration_ms:number|null;cost_usd:number;platform_cost_usd:number;missing_context:number;cost_per_test_usd:number|null;cost_per_student_usd:number|null;projected_cost_per_1000_tests_usd:number|null;by_topic:{topic:string;cost_usd:number;calls:number;tests:number;cost_per_test_usd:number|null}[]};question_bank:{observed_requests:number;full_hits:number;partial_hits:number;misses:number;served_questions:number;requested_questions:number;question_hit_rate:number|null}; learning:{completed_sessions:number;covered_sessions:number;event_count:number;coverage_rate:number|null}; alerts:{code:string;severity:string;message:string}[] }
export default function PipelineHealth() {
  const [data,setData]=useState<Health|null>(null)
  const [error,setError]=useState('')
  async function load(){ const {data:{session}}=await createClient().auth.getSession(); if(!session)return; const response=await fetch('/api/admin/pipeline-health',{headers:{Authorization:`Bearer ${session.access_token}`}}); if(response.ok)setData(await response.json()); else setError('Pipeline sağlığı alınamadı.') }
  useEffect(()=>{ void load() },[])
  return <div className="card" style={{marginBottom:'1rem'}}><div style={{display:'flex',justifyContent:'space-between',gap:8}}><strong style={{color:'var(--primary)'}}>🚦 Performans, havuz ve AI maliyeti</strong><button className="btn btn-sm" onClick={()=>void load()}>Yenile</button></div>{error&&<div style={{color:'var(--red)',fontSize:12,marginTop:8}}>{error}</div>}{data&&<><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(150px,1fr))',gap:8,marginTop:10,fontSize:12}}><div>30 günlük AI çağrısı<br/><strong>{data.ai.calls}</strong></div><div>AI p95 gecikme<br/><strong>{data.ai.p95_duration_ms===null?'—':`${Math.round(data.ai.p95_duration_ms/1000)} sn`}</strong></div><div>Toplam maliyet<br/><strong>${data.ai.cost_usd.toFixed(4)}</strong></div><div>Test başına<br/><strong>{data.ai.cost_per_test_usd===null?'—':`$${data.ai.cost_per_test_usd.toFixed(4)}`}</strong></div><div>1.000 test tahmini<br/><strong>{data.ai.projected_cost_per_1000_tests_usd===null?'—':`$${data.ai.projected_cost_per_1000_tests_usd.toFixed(2)}`}</strong></div><div>Havuz soru oranı<br/><strong>{data.question_bank.question_hit_rate===null?'Yeni ölçüm bekleniyor':`%${Math.round(data.question_bank.question_hit_rate*100)}`}</strong></div></div><div style={{fontSize:12,marginTop:10}}>Tam havuz: {data.question_bank.full_hits} · Hibrit: {data.question_bank.partial_hits} · AI: {data.question_bank.misses}</div>{data.ai.by_topic.length>0&&<div style={{marginTop:10,fontSize:12}}><strong>Konu bazında en yüksek maliyet</strong>{data.ai.by_topic.slice(0,5).map(row=><div key={row.topic} style={{borderTop:'1px solid var(--border)',paddingTop:5,marginTop:5}}>{row.topic}: ${row.cost_usd.toFixed(4)} · {row.tests} test</div>)}</div>}{data.alerts.length?<div style={{marginTop:10,padding:8,borderRadius:8,background:'var(--red-bg)',color:'var(--red)',fontSize:12}}>{data.alerts.map(a=><div key={a.code}>⚠️ {a.message}</div>)}</div>:<div style={{marginTop:10,color:'var(--green)',fontSize:12}}>✓ Son {data.period_hours} saatte eşik aşımı yok.</div>}</>}</div>
}
