-- Canonical Learning Catalog & Learning Graph content pipeline v1.
-- Builds only from reviewed taxonomy and first-party MEB resource metadata.
-- No learning-objective code is inferred from free text or generated by AI.

CREATE TABLE IF NOT EXISTS public.learning_objective_catalog (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  objective_code text NOT NULL UNIQUE,
  title text NOT NULL CHECK (char_length(btrim(title)) >= 3),
  level text NOT NULL,
  grade text NOT NULL,
  subject text NOT NULL,
  unit text,
  topic text,
  source_type text NOT NULL CHECK (source_type IN ('meb', 'manual', 'import')),
  source_reference text,
  verification_status text NOT NULL DEFAULT 'candidate'
    CHECK (verification_status IN ('candidate', 'verified', 'rejected')),
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS learning_objective_catalog_dimension_idx
  ON public.learning_objective_catalog (subject, grade, unit)
  WHERE is_active = true AND verification_status = 'verified';

CREATE TABLE IF NOT EXISTS public.learning_content_node_mappings (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  source_type text NOT NULL CHECK (source_type IN (
    'curriculum', 'meb_resource', 'meb_chunk', 'exam_resource', 'quiz_topic'
  )),
  source_id text NOT NULL,
  node_id uuid NOT NULL REFERENCES public.learning_graph_nodes(id) ON DELETE CASCADE,
  mapping_method text NOT NULL CHECK (mapping_method IN ('exact', 'reviewed_alias', 'manual')),
  confidence numeric(4,3) NOT NULL CHECK (confidence BETWEEN 0 AND 1),
  is_verified boolean NOT NULL DEFAULT false,
  reviewed_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (source_type, source_id, node_id)
);

CREATE INDEX IF NOT EXISTS learning_content_node_mappings_source_idx
  ON public.learning_content_node_mappings (source_type, source_id);
CREATE INDEX IF NOT EXISTS learning_content_node_mappings_node_idx
  ON public.learning_content_node_mappings (node_id);
CREATE INDEX IF NOT EXISTS learning_content_node_mappings_reviewer_idx
  ON public.learning_content_node_mappings (reviewed_by)
  WHERE reviewed_by IS NOT NULL;

CREATE TABLE IF NOT EXISTS public.learning_catalog_review_queue (
  dimension_key text PRIMARY KEY,
  observed_label text NOT NULL,
  observed_subject text NOT NULL DEFAULT 'Genel',
  occurrence_count integer NOT NULL DEFAULT 0 CHECK (occurrence_count >= 0),
  student_count integer NOT NULL DEFAULT 0 CHECK (student_count >= 0),
  sample_grades jsonb NOT NULL DEFAULT '[]'::jsonb,
  status text NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'mapped', 'dismissed')),
  mapped_node_id uuid REFERENCES public.learning_graph_nodes(id) ON DELETE SET NULL,
  reviewed_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  reviewed_at timestamptz,
  first_seen_at timestamptz,
  last_seen_at timestamptz,
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS learning_catalog_review_queue_priority_idx
  ON public.learning_catalog_review_queue (status, occurrence_count DESC, last_seen_at DESC);
CREATE INDEX IF NOT EXISTS learning_catalog_review_queue_node_idx
  ON public.learning_catalog_review_queue (mapped_node_id)
  WHERE mapped_node_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS learning_catalog_review_queue_reviewer_idx
  ON public.learning_catalog_review_queue (reviewed_by)
  WHERE reviewed_by IS NOT NULL;

ALTER TABLE public.learning_objective_catalog ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.learning_content_node_mappings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.learning_catalog_review_queue ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS learning_objective_catalog_verified_read
  ON public.learning_objective_catalog;
CREATE POLICY learning_objective_catalog_verified_read
  ON public.learning_objective_catalog FOR SELECT TO authenticated
  USING (is_active = true AND verification_status = 'verified');

REVOKE INSERT, UPDATE, DELETE ON public.learning_objective_catalog FROM anon, authenticated;
GRANT SELECT ON public.learning_objective_catalog TO authenticated;
GRANT ALL ON public.learning_objective_catalog TO service_role;
REVOKE ALL ON public.learning_content_node_mappings FROM PUBLIC, anon, authenticated;
REVOKE ALL ON public.learning_catalog_review_queue FROM PUBLIC, anon, authenticated;
GRANT ALL ON public.learning_content_node_mappings, public.learning_catalog_review_queue TO service_role;

CREATE OR REPLACE FUNCTION public.canonical_learning_grade(value text)
RETURNS text LANGUAGE sql IMMUTABLE PARALLEL SAFE
SET search_path = public, pg_temp
RETURN regexp_replace(
  regexp_replace(lower(regexp_replace(btrim(coalesce(value, '')), '\s+', ' ', 'g')),
    '([0-9]+)\s*\.\s*sınıf', '\1. sınıf', 'g'),
  '^orta okul', 'ortaokul'
);

REVOKE ALL ON FUNCTION public.canonical_learning_grade(text) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.canonical_learning_grade(text) TO service_role;

CREATE OR REPLACE FUNCTION public.sync_learning_catalog_v1()
RETURNS TABLE(subject_nodes integer, unit_nodes integer, topic_nodes integer,
  part_of_edges integer, source_mappings integer, review_candidates integer)
LANGUAGE plpgsql SECURITY INVOKER
SET search_path = public, pg_temp
AS $$
DECLARE v_subjects integer; v_units integer; v_topics integer;
  v_edges integer; v_mappings integer; v_candidates integer;
BEGIN
  INSERT INTO public.learning_graph_nodes
    (node_key, node_type, label, subject, grade, level, source_type, metadata, is_active)
  SELECT DISTINCT
    'subject:' || md5(concat_ws('|', lower(c.level), public.canonical_learning_grade(c.grade), lower(c.subject))),
    'subject', c.subject, c.subject, public.canonical_learning_grade(c.grade), lower(c.level),
    'curriculum', jsonb_build_object('catalog_version', 'v1'), true
  FROM public.curriculum c WHERE c.is_active = true
  ON CONFLICT (node_key) DO UPDATE SET
    label = EXCLUDED.label, subject = EXCLUDED.subject, grade = EXCLUDED.grade,
    level = EXCLUDED.level, is_active = true, updated_at = now();
  GET DIAGNOSTICS v_subjects = ROW_COUNT;

  INSERT INTO public.learning_graph_nodes
    (node_key, node_type, label, subject, grade, level, source_type, metadata, is_active)
  SELECT DISTINCT
    'subject:' || md5(concat_ws('|', lower(r.level), public.canonical_learning_grade(r.grade), lower(r.subject))),
    'subject', r.subject, r.subject, public.canonical_learning_grade(r.grade), lower(r.level),
    'meb_resource', jsonb_build_object('catalog_version', 'v1'), true
  FROM public.meb_resources r
  WHERE coalesce(btrim(r.health_flag), '') = ''
  ON CONFLICT (node_key) DO UPDATE SET
    label = EXCLUDED.label, subject = EXCLUDED.subject, grade = EXCLUDED.grade,
    level = EXCLUDED.level, is_active = true, updated_at = now();

  INSERT INTO public.learning_graph_nodes
    (node_key, node_type, label, subject, grade, level, source_type, metadata, is_active)
  SELECT DISTINCT
    'unit:' || md5(concat_ws('|', lower(r.level), public.canonical_learning_grade(r.grade),
      lower(r.subject), public.learning_dimension_key(r.unit))),
    'unit', regexp_replace(btrim(r.unit), '\s+', ' ', 'g'), r.subject,
    public.canonical_learning_grade(r.grade), lower(r.level), 'meb_resource',
    jsonb_build_object('catalog_version', 'v1', 'verification_status', 'verified'), true
  FROM public.meb_resources r
  WHERE coalesce(btrim(r.health_flag), '') = '' AND nullif(btrim(r.unit), '') IS NOT NULL
  ON CONFLICT (node_key) DO UPDATE SET
    label = EXCLUDED.label, subject = EXCLUDED.subject, grade = EXCLUDED.grade,
    level = EXCLUDED.level, metadata = EXCLUDED.metadata,
    is_active = true, updated_at = now();
  GET DIAGNOSTICS v_units = ROW_COUNT;

  INSERT INTO public.learning_graph_nodes
    (node_key, node_type, label, subject, source_type, metadata, is_active)
  SELECT DISTINCT 'topic:canonical:' || md5(concat_ws('|', lower(a.canonical_subject),
      public.learning_dimension_key(a.canonical_topic))),
    'topic', a.canonical_topic, a.canonical_subject, 'reviewed_taxonomy',
    jsonb_build_object('catalog_version', 'v1', 'verification_status', 'reviewed'), true
  FROM public.learning_topic_aliases a WHERE a.review_status = 'reviewed'
  ON CONFLICT (node_key) DO UPDATE SET
    label = EXCLUDED.label, subject = EXCLUDED.subject, metadata = EXCLUDED.metadata,
    is_active = true, updated_at = now();
  GET DIAGNOSTICS v_topics = ROW_COUNT;

  INSERT INTO public.learning_graph_edges
    (source_node_id, target_node_id, edge_type, confidence, rationale, source_type, is_verified)
  SELECT u.id, s.id, 'part_of', 1.000,
    'MEB kaynağındaki doğrulanmış ders-sınıf-ünite hiyerarşisi', 'meb_resource', true
  FROM public.learning_graph_nodes u
  JOIN public.learning_graph_nodes s
    ON s.node_key = 'subject:' || md5(concat_ws('|', u.level,
      public.canonical_learning_grade(u.grade), lower(u.subject)))
  WHERE u.node_type = 'unit' AND u.source_type = 'meb_resource'
  ON CONFLICT (source_node_id, target_node_id, edge_type) DO UPDATE SET
    confidence = 1.000, rationale = EXCLUDED.rationale,
    source_type = EXCLUDED.source_type, is_verified = true, updated_at = now();
  GET DIAGNOSTICS v_edges = ROW_COUNT;

  INSERT INTO public.learning_content_node_mappings
    (source_type, source_id, node_id, mapping_method, confidence, is_verified, metadata)
  SELECT 'meb_resource', r.id::text, u.id, 'exact', 1.000, true,
    jsonb_build_object('resource_title', r.title)
  FROM public.meb_resources r
  JOIN public.learning_graph_nodes u
    ON u.node_key = 'unit:' || md5(concat_ws('|', lower(r.level),
      public.canonical_learning_grade(r.grade), lower(r.subject), public.learning_dimension_key(r.unit)))
  WHERE coalesce(btrim(r.health_flag), '') = ''
  ON CONFLICT (source_type, source_id, node_id) DO UPDATE SET
    confidence = 1.000, is_verified = true, metadata = EXCLUDED.metadata, updated_at = now();
  GET DIAGNOSTICS v_mappings = ROW_COUNT;

  INSERT INTO public.learning_catalog_review_queue
    (dimension_key, observed_label, observed_subject, occurrence_count,
     student_count, sample_grades, first_seen_at, last_seen_at, updated_at)
  SELECT public.learning_dimension_key(e.subject) || '|' || public.learning_dimension_key(e.topic),
    max(e.topic), max(e.subject), count(*)::integer, count(distinct e.student_id)::integer,
    coalesce(jsonb_agg(distinct e.grade) FILTER (WHERE e.grade IS NOT NULL), '[]'::jsonb),
    min(e.occurred_at), max(e.occurred_at), now()
  FROM public.learning_events e
  WHERE NOT EXISTS (
    SELECT 1 FROM public.learning_graph_nodes n
    WHERE n.node_type = 'topic' AND n.is_active = true
      AND public.learning_dimension_key(n.subject) = public.learning_dimension_key(e.subject)
      AND public.learning_dimension_key(n.label) = public.learning_dimension_key(e.topic)
  )
  GROUP BY public.learning_dimension_key(e.subject), public.learning_dimension_key(e.topic)
  ON CONFLICT (dimension_key) DO UPDATE SET
    observed_label = EXCLUDED.observed_label,
    observed_subject = EXCLUDED.observed_subject,
    occurrence_count = EXCLUDED.occurrence_count,
    student_count = EXCLUDED.student_count,
    sample_grades = EXCLUDED.sample_grades,
    first_seen_at = EXCLUDED.first_seen_at,
    last_seen_at = EXCLUDED.last_seen_at,
    updated_at = now();
  GET DIAGNOSTICS v_candidates = ROW_COUNT;

  RETURN QUERY SELECT v_subjects, v_units, v_topics, v_edges, v_mappings, v_candidates;
END;
$$;

REVOKE ALL ON FUNCTION public.sync_learning_catalog_v1() FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.sync_learning_catalog_v1() TO service_role;

COMMENT ON TABLE public.learning_objective_catalog IS
  'Verified learning objectives only; objective codes must come from MEB/manual authoritative sources and are never AI-invented.';
COMMENT ON TABLE public.learning_content_node_mappings IS
  'Auditable links between source content and canonical Learning Graph nodes.';
COMMENT ON TABLE public.learning_catalog_review_queue IS
  'Observed event topics that require human mapping to the canonical curriculum graph.';
COMMENT ON FUNCTION public.sync_learning_catalog_v1() IS
  'Idempotently syncs curriculum subjects, healthy MEB units, reviewed topics, verified hierarchy edges and review candidates.';
